// <auto-generated />
using FormularioVET;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FormularioVET.Migrations
{
    [DbContext(typeof(BDveteriano))]
    [Migration("20210428191849_CriacaoTabelaTypeOfVet")]
    partial class CriacaoTabelaTypeOfVet
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FormularioVET.Customer", b =>
                {
                    b.Property<int>("CustomerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AdressCustumer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailCustumer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameCustumer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CustomerID");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("FormularioVET.Pet", b =>
                {
                    b.Property<int>("PetID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CustomerID")
                        .HasColumnType("int");

                    b.Property<string>("NamePet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeOfPet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WeightPet")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PetID");

                    b.ToTable("Pets");
                });

            modelBuilder.Entity("FormularioVET.TypeOfVet", b =>
                {
                    b.Property<int>("TypeOfVetID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("typeofAnimal")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TypeOfVetID");

                    b.ToTable("TypeOfVets");
                });
#pragma warning restore 612, 618
        }
    }
}
